import React from "react";
import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import TanStackProvider from "@/components/providers/TanStackProvider";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <ClerkProvider>
      <html lang="en">
        <TanStackProvider>
          <body className="dark:bg-black dark:text-white">{children}</body>
          <Toaster richColors position="bottom-right" />
        </TanStackProvider>
      </html>
    </ClerkProvider>
  );
};

export default RootLayout;
