import React from "react";
import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import TanStackProvider from "@/components/providers/TanStackProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <ClerkProvider>
      <TanStackProvider>
        <html lang="en">
          <body className="dark:bg-black dark:text-white">{children}</body>
        </html>
      </TanStackProvider>
    </ClerkProvider>
  );
};

export default RootLayout;
